version: "3"

services:
  spark-iceberg:
    build: spark/
    depends_on:
      - metastore
    container_name: spark-iceberg
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
      - HADOOP_HOME=/opt/hadoop
      - HIVE_HOME=/opt/hive
      - SPARK_HOME=/opt/spark
      - PYSPARK_PYTON=/usr/bin/python3.9
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/hive/bin:/opt/spark/bin
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks
    ports:
      - 8888:8888
      - 8080:8080
  metastore:
    image: postgres:13.4-bullseye
    container_name: metastore
    environment:
      - POSTGRES_PASSWORD=quickstart
      - POSTGRES_DB=metastore
    volumes:
      - ./metastore/data:/var/lib/postgresql/data